### DISCUSSION TITLE
Docker Compose Template for Synology NAS

### DISCUSSION THREAD

**Discussion by arxipelagos** [tphakala/birdnet-go#134] [Show and tell]
Here is my working Template for a Docker Project on a Synology NAS (DS1821+) running with an RTSP Audio Stream.

```
version: "3.3"
services:
    birdnet-go:
        image: ghcr.io/tphakala/birdnet-go:latest
        ports:
            - 5803:8080
        volumes:
            - "./config:/config"
            - "./data:/data"
        restart: unless-stopped
        environment:
            TZ: Europe/Vienna
        mem_limit: 8g
networks:
  default:
    driver: bridge
```
