### DISCUSSION TITLE
May 23rd, 2024 release

### DISCUSSION THREAD

**Discussion by tphakala** [tphakala/birdnet-go#174] [Announcements]
### 🚀 Features

- *(birdweather)* Added location fuzzing support for BirdWeather uploads, requires support for BirdWeather.com
- *(audio)* Audio source device is now user configurable

### 🐛 Bug Fixes

- *(audio)* Audio clip extraction fixed for occassional non-contiguous clips

### 🚜 Refactor

- *(conf)* Move default config file from .go to .yaml and add proper default value initialization
- *(conf)* Update audio export settings in updateconfig.go and realtime.go

### 🏗️ Building

- *(deps)* Bump golang.org/x/text from 0.14.0 to 0.15.0
- *(deps)* Bump golang.org/x/crypto from 0.22.0 to 0.23.0
- *(deps)* Bump github.com/prometheus/client_golang

### ⚙️ Miscellaneous Tasks

- Update go version to 1.22.3
- Update golang version to 1.22.3
- Bump HTMX version from 1.9.11 to 1.9.12
- Bump daisyUI to 4.11.1
- Update custom.css to fix theme controller styles
- Update tailwindcss to v3.4.3
- Hide "Detections" column on smaller screens
- Update audio buffer initialization in realtime analysis
- Remove unused import and struct field in audiobuffer.go

<hr /><em>This discussion was created from the release <a href='https://github.com/tphakala/birdnet-go/releases/tag/v0.5.3'>May 23rd, 2024 release</a>.</em>

**Comment by tphakala** [comment]
Please note that this version updates config.yaml file structure for realtime audio section quite bit, you need to manually update config.yaml file for new format for now.

```
# Realtime processing settings
realtime:
    interval: 15 # duplicate prediction interval in seconds
    processingtime: false # true to report processing time for each prediction
    audio:
        source: "sysdefault"
        export:
            enabled: true # true to export audio clips containing indentified bird calls
            path: clips/    # path to audio clip export directory
            type: wav       # only wav supported for now
        retention:
            enabled: true
```

There is a new `source `setting for `audio `, this allows user selectable audio source on Linux, by default it is set to sysdefault and it should select default capture device of your system. Valid settings for this are all sources (sysdefault, default, dsnoop, etc) that are listed with arecord -L

```
# arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
sysdefault
    Default Audio Device
default
    Default High-Pass Filtered Device
filtered
    High-Pass Filtered Capture Device
hw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Front output / input
dsnoop:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample snooping device
```

Hardware device name is also a valid setting, you can see these with `arecord -l`

```
arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

in this case

```
realtime:
    audio:
        source: "USB Audio Device"
```

would be a valid setting
