### DISCUSSION TITLE
June 1st, 2024 release v0.5.4

### DISCUSSION THREAD

**Discussion by tphakala** [tphakala/birdnet-go#185] [Announcements]
### 🚀 Features

- *(audio)* Disk usage based audio clip retention policy, enabled by default with 80% disk usage treshold
- *(conf)* Privacy filter Confidence threshold setting
- *(conf)* Dog bark filter Confidence threshold setting
- *(conf)* Dog bark filter time to remember bark setting

### 🐛 Bug Fixes

- *(webui*) Fix Settings interface load error

### 🚜 Refactor

- *(conf)* Refactor configuration package to improve settings handling, easier access to settings in code
- *(audio)* Audio clip retention policy setting: none, age, usage
- *(audio)* Age base audio clip retention policy accepts time in days, weeks, months and years instead of hours
- *(conf)* Many settings renamed

### ⚙️ Miscellaneous Tasks

- Update go.mod with github.com/mitchellh/mapstructure v1.5.0

<hr /><em>This discussion was created from the release <a href='https://github.com/tphakala/birdnet-go/releases/tag/v0.5.4'>v0.5.4</a>.</em>

**Comment by isZumpo** [comment]
Great work on all of these new features! I can now also verify that both arm64 and amd64 are available for this release of the docker image :)

![Screenshot_20240601-105649.png](https://github.com/tphakala/birdnet-go/assets/8884086/27758f6f-5653-4756-acc5-52dda94f251c)

**Comment by tphakala** [comment]
This new release adds a new disk utillization based audio clip retention policy. This new retention policy is enabled by default and it is set to keep disk utilization at 80% level, once this threshold is exceeded old clips will be deleted, database entries are left intact. Cleanup policy will delete low confidence recordings first, and by detault it keeps 10 recordings per species for each month, this is to protect rare sigthings from being deleted.

Age based cleanup policy is also reworked somewhat, instead of hours clip age is now configured as hours, weeks, months or years. If you would like to store audio clips for 6 weeks and keep no recordings for any species over that time you would configure

```
retention:
  policy: age
  maxage: 6w
  minclips: 0
```

**Please recreate your config file**

I have renamed few configuration settings as things evolve, and because there is not yet any automatic method for updating config file I would highly recommend you to backup your current config file by renaming it and let birdnet-go to create a new config with new structure, and copy your settings over to new file.

**Reply by tphakala** [reply]
It seems that I messed up default settings for human privacy and dog bark filters, please add confidence setting for dogbark filter with value of 0.1 or lower and fix a typo for confidence on privacyfilter.

  privacyfilter:          # Privacy filter prevents audio clip saving if human voice 
    enabled: true         # is detected durin audio capture
    confidence: 0.05      # threshold for human voice detection

  dogbarkfilter:
    enabled: true
    confidence: 0.1       # confidence threshold for dog bark detection
    remember: 5           # number of minutes to remember dog barks

**Reply by sclitheroe** [reply]
Hi,

Does this look correct?  (see below)... Thanks so much for Birdnet-Go, I LOVE it!

```
privacyfilter: # Privacy filter prevents audio clip saving if human voice
        enabled: true # is detected durin audio capture
        confidence: 0.1
        threshold: 0.05 # threshold for human voice detection
    dogbarkfilter:
        enabled: true
        confidence: 0.1 # confidence threshold for dog bark detection
        remember: 5 # number of minutes to remember dog barks
```
