### DISCUSSION TITLE
Dynamic Threshold for Positive Bird Call Detections

### DISCUSSION THREAD

**Discussion by tphakala** [tphakala/birdnet-go#211] [Announcements]
I have added a Dynamic Threshold for positive bird call detections, feature is available in latest :dev container release. This feature allows the detection thresholds to adapt based on recent high-confidence detections. Goal of this feature is to keep threshold low for species which are detected with high certaintity at your area.

The Dynamic Threshold can be configured with the following options:

```
realtime:
  dynamicthreshold:
    enabled: true         # true to enable dynamic confidence threshold
    trigger: 0.90         # dynamic threshold is activated on detections at this confidence level
    min: 0.20             # dynamic threshold will not go lower than this
    validhours: 24        # number of hours to consider for dynamic confidence
```

- **enabled**: Set to true to enable the dynamic confidence threshold feature.
- **trigger**: The confidence level at which the dynamic threshold is activated. If a bird call is detected with confidence over this value, the threshold for positive matches of that species will be lowered for subsequent calls.
- **min**: The minimum value to which the dynamic threshold can be lowered. This ensures that the threshold does not drop below unwanted level.
- **validhours**: The number of hours during which the dynamic threshold adjustments remain valid. After this period, the dynamic threshold is reset. 

**How It Works**

When a bird call detection exceeds the configured trigger threshold, the dynamic threshold for that species is adjusted to a lower value, making it easier for subsequent detections of the same species to be considered positive matches. The dynamic threshold has multiple levels and will not be lowered below the configured minimum value.

1. Initial Detection: A bird call is detected with a confidence level above the trigger threshold.
2. Threshold Adjustment: The dynamic threshold for that species is lowered incrementally.
3. Subsequent Detections: Subsequent detections of the same species are more likely to be considered positive matches if they exceed the new, lower threshold.
4. Reset: If no high-confidence detections occur within the configured valid hours, the dynamic threshold is reset to the original trigger value.
