### DISCUSSION TITLE
Anyone have any recommendations on serving an rtsp audio stream from a raspberry pi?

### DISCUSSION THREAD

**Discussion by have-no-clue-what-im-doing** [tphakala/birdnet-go#224] [General]
I've been doing a bunch of research but I am not finding in solid documentation on this. There a specific library or package anyone suggests?

**Comment by tphakala** [comment]
Following uses ffmpeg to capture audio from usb sound card and it uses MediaMTX (previously known as rtsp-simple-server) to publish stream for network clients

`sudo apt install ffmpeg
`

Download and install MediaMTX

```
wget https://github.com/bluenviron/mediamtx/releases/latest/download/mediamtx_linux_amd64.tar.gz
tar xzvf mediamtx_*_linux_arm64v8.tar.gz
sudo mv mediamtx /usr/local/bin/
```

Edit configuration file mediamtx.yml

Add the following content to the end of configuration file

```
paths:
  stream:
    runOnInit: ffmpeg -f alsa -i default -acodec libmp3lame -f rtsp -rtsp_transport tcp rtsp://localhost:8554/stream
    runOnInitRestart: yes
```

Start MediaMTX with the configuration file

`mediamtx mediamtx.yml
`

Stream is now available at rtsp://your-pi-ip-address:8554/stream.

If you get errors about not being able to open device try these for ffmpeg `-i default` setting instead

```
-i sysdefault
-i pulse
```

**Reply by have-no-clue-what-im-doing** [reply]
Thanks @tphakala !

I did get this working with a few minor changes:

First, `https://github.com/bluenviron/mediamtx/releases/latest/download/mediamtx_linux_amd64.tar.gz` was giving me a 404 and it's amd64, so I went ahead and downloaded the arm version: `https://github.com/bluenviron/mediamtx/releases/download/v1.8.3/mediamtx_v1.8.3_linux_arm64v8.tar.gz`

And for the `mediamtx.yml` I kept getting errors about the "no device" no matter the setting, so I set the -i switch to `hw:1,0` after running `arecord -l` to get a list of hardware devices.

I also had to set my channel to 1 since it kept trying to use 2 and erroring out. Here is what I added to my mediamtx.yml:

```
paths:
 stream:
  runOnInit: ffmpeg -f alsa -channels 1 -i hw:1,0 -acodec libmp3lame -f rtsp -rtsp_transport tcp rtsp://localhost:8554/stream
  runOnInitRestart: yes
```

After all this I finally got it working. Just putting this here for reference to anyone else having trouble setting this up.

**Comment by isZumpo** [comment]
Hi, I see that @tphakala already responded. I am using a similar setup in my Kubernetes cluster, with containers instead. Here are the relevant snippets of my pod specifications that could be translated into docker easily if you want to use it:

**RTSP client running on Raspberry Pi with mic**
```yaml
 - image: lscr.io/linuxserver/ffmpeg:6.1.1
    name: ffmpeg
    args:
    - -f
    - alsa
    - -i
    - plughw:0
    - -f
    - "rtsp"
    - rtsp://birdnet-rtsps-server.birdnet.svc.cluster.local:8554/mystream
    env:
    - name: ALSA_CARD
      value: '1'
```

**RTSP server which client talks to**
```yaml
 - image: bluenviron/mediamtx:latest
    name: mediamtx
    env:
    - name: MTX_PROTOCOLS
      value: tcp
    ports:
      - name: rtsp
        containerPort: 8554
        protocol: TCP
```

**Birdnet**
```yaml
  args:
  - realtime
  - --rtsp
  - rtsp://birdnet-rtsps-server.birdnet.svc.cluster.local:8554/mystream
  - --rtsptransport
  - tcp
```

Swap the **birdnet-rtsps-server.birdnet.svc.cluster.local** address for whatever ip you decide to run the rtsp server at. 

Bit of midsummer celebrations here in Sweden today. So I did unfortunately not have time to translate these into docker commands for you. But let me know if you need assistance with it 😊
