### DISCUSSION TITLE
Last seen bird card (with picture) in Home Assistant

### DISCUSSION THREAD

**Discussion by PovilasID** [tphakala/birdnet-go#242] [Show and tell]
Hey,

I wanted to learn how does a bird that I am hearing looks, so I spun up this app but I wanted to see in my Home Assistant as nice novelty panel, so here is how I did it.
![image](https://github.com/tphakala/birdnet-go/assets/396243/71e251c2-02d2-4de5-8122-c17cfb28bba5)
_P.S. You can make a prettier/more compact version but this one does not need any plugins like stack-in-card will work on stock HA_

If you want the same:
## Pre-requsites:
- MQTT server. MQTT is often used by Home Assistant and you can install it as plugin or use any other tutorial

## Birdnet-go config
In the `config.yaml` set `enabled: false` under `mqtt` and provide address and credentials to MQTT server

## Home Assistant config
Assuming you have MQTT enabled it may get auto discovered check "Developer" section under states if there is not `birdnet` already available if not in the `configuration.yaml` add:
```
mqtt:
  sensor:
    - name: "Garden Birds"
      state_topic: "birdnet"
      json_attributes_topic: "birdnet"
      value_template: "{{ value_json.CommonName }}"
```
Make sure that topics from HA and birdnet-go match. To also get a picture also add a an image template:
```
template:
  - image:
      - name: Garden bird picture
        verify_ssl: false
        url: "{{ state_attr('sensor.garden_birds','BirdImage')['URL'] }}"
```
To dashboard panel just edit the dashboard add a Manual card and paste this in:
```
square: false
type: grid
cards:
  - type: entity
    entity: sensor.garden_birds
    state_color: false
    icon: mdi:bird
  - type: picture
    image_entity: image.garden_bird_picture
  - type: entities
    entities:
      - type: attribute
        entity: sensor.garden_birds
        name: Confidence
        attribute: Confidence
        icon: mdi:percent
      - type: attribute
        entity: sensor.garden_birds
        name: Time
        attribute: BeginTime
        icon: mdi:clock
columns: 1
``` 
You can customize the panel any way you like adding picture credit or scientific name etc.

Credit: https://github.com/mcguirepr89/BirdNET-Pi/discussions/342#discussioncomment-7080211
