### DISCUSSION TITLE
mysql database output

### DISCUSSION THREAD

**Discussion by unosonic** [tphakala/birdnet-go#30] [Q&A]
I've mysql output enabled in the config file, but birdnet-go still creates table files in the output directory. 
  ```
mysql:
    enabled: true
    username: birdnet
    password: my_pw
    database: birdnet
    host: localhost
    port: 3306
```
file and sqlite outputs are disabled, database and user exist and work. am I missing something?
