### DISCUSSION TITLE
Deep detection feature for more reliable results

### DISCUSSION THREAD

**Discussion by tphakala** [tphakala/birdnet-go#302] [Announcements]
Current dev branch container images contain a new "deep detection" feature which is enabled when the BirdNET overlap value is increased to 2.7. This increases detection frequency by reducing the audio analysis step from the default 1.5 seconds down to 300 milliseconds, allowing more BirdNET results for each call. With this increased "sampling frequency," BirdNET-Go requires 4 or more results of the same species before accepting a detection.

This feature has been in the code for a few months already, and on my nodes, it seems to work very well in reducing false positive results, even with very low confidence threshold values like 0.3.

Since this increases times AI inference is executed, it is somewhat demanding for CPU utilization. I am personally running this on RPI 5 (and on rather powerful Intel Windows system), but I expect RPI 4 to be adequate for this as well. Anything below that is unlikely to perform AI analysis fast enough to keep up. If your system can't keep up BirdNET-Go will log warning messages to log 

"WARNING: BirdNET processing time (335.538286ms) exceeded buffer length (300ms) for source malgo"

few of these warnings from time to time are fine, but if you see constant flood of warnings you need to reduce overlap value.

The plan is to add a UI element which would enable this "deep detection" with a single click, and the overlap value would be automatically adjusted based on your hardware performance.

**Comment by farski** [comment]
Are updated container images being published somewhere, or should we be building them ourselves?

**Reply by tphakala** [reply]
No need to build yourself. The dev branch image is built automatically by GitHub workflows anytime there is a commit to this GitHub repo. Running "docker pull ghcr.io/tphakala/birdnet-go:dev" always pulls the latest image.

**Reply by farski** [reply]
Ah perfect, thank you

**Reply by jkrauska** [reply]
might want to automate the update to happen in systemd... maybe a weekly/nightly intentional restart to pull latest?

**Reply by farski** [reply]
Good idea, @jkrauska. I revised my [install guide](https://github.com/tphakala/birdnet-go/discussions/307) to include a cron to handle the update. (I used cron rather than systemd only because I'm bad at systemd.)

**Reply by kx1t** [reply]
Most people use the `containrrr/watchtower` container to automatically detect if new container build images have become available, and to download/deploy these images.

```yaml
  watchtower:
    image: containrrr/watchtower:latest
    tty: true
    container_name: watchtower
    hostname: watchtower
    restart: always
    environment:
      TZ: ${FEEDER_TZ}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: 0 0 * * * *
      WATCHTOWER_ROLLING_RESTART: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
