### DISCUSSION TITLE
Late 2024 alternate install walkthrough

### DISCUSSION THREAD

**Discussion by farski** [tphakala/birdnet-go#307] [Show and tell]
In case this is helpful for anyone, I just rebuilt my birdnet box. I had been running birdnet-go for a while, but using the binaries, and on a Pi that had previously been running BirdNET-Pi. I started over, using Docker from the beginning. This is on a Pi 4B. I did things a bit differently than the standard [install docs](https://github.com/tphakala/birdnet-go/blob/main/doc/installation.md).

These instructions assume some basic Linux and Docker knowledge. I know not everyone installing birdnet-go does computers for a living, so if anything needs to be expanded, please ask – I'm happy to explain.

1. Installed Raspberry Pi OS Lite on an SD card using the RP [imager](https://www.raspberrypi.com/software/)
2. Installed Docker Engine by following [their guide](https://docs.docker.com/engine/install/debian/#install-using-the-repository). (Note: a lot of links on Docker's website will take you to the install guide for Docker Desktop, even when you're on pages for Docker Engine. If you want only Docker Engine, make sure you know what page you're looking at).
3. Followed the steps to [manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
4. I made two directories for birdnet-go assets: `~/birdnet-go/data` and `~/birdnet-go/config`
5. Follow the steps in [Deciding ALSA_CARD value](https://github.com/tphakala/birdnet-go/blob/main/doc/installation.md#deciding-alsa_card-value)
6. Created a `~/birdnet-go/compose.yml` file
    ```yaml
    services:
      birdnet-go:
        restart: unless-stopped
        image: ghcr.io/tphakala/birdnet-go:dev
        ports:
          - 80:8080
        environment:
          - ALSA_CARD=1
          - TZ=America/New_York
        devices:
          - /dev/snd:/dev/snd
        volumes:
          - $HOME/birdnet-go/config:/config
          - $HOME/birdnet-go/data:/data
    ```
    > Note that this is running the `dev` release of birdnet-go, which may be more experimental or unstable than you want.
7. Run `docker compose up -d`. Because of the `restart` directive in `compose.yml`, Docker Compose should keep birdnet-go running, even in the event of a crash or something like that.
8. I also wanted to backup my birdnet database everyday, so I added this to my crontab: 

    `15 0 * * * cp /home/birdnet/birdnet-go/data/birdnet.db /home/birdnet/birdnet-go/data/birdnet.bak.db && AWS_ACCESS_KEY_ID=tktktk AWS_SECRET_ACCESS_KEY="tktktk" AWS_DEFAULT_REGION=tktk aws s3 cp /home/birdnet/birdnet-go/data/birdnet.bak.db s3://my-backup-bucket/daily/birdnet.bak.db`.

    You'd need the AWS CLI (I used `sudo apt install awscli` even though that's not what AWS recommends). You'll need to sort out creating a bucket in AWS and setting up the key/secret if you wanted to do this. Or you could do something similar with many other file hosting services, rsync, sftp, etc. The only tricky bit in here is that `aws s3` does an MD5 check to ensure the upload is valid, and the database file may change during the upload. So first this copies the DB to a backup file and pushes that to S3.
10. (Update: 2024-12-20) I've also added another crontab entry, to automatically update the `dev` docker image and restart the container every night:
    `15 1 * * * cd /home/birdnet/birdnet-go && docker compose pull && docker compose up -d`
11. (Update: 2025-08-04) A couple other crontab entries I've added over time to keep up with maintenance tasks:
    `30 1 * * * docker image prune` (the nightly images accumulate over time)
    `45 1 * * * rm /home/birdnet/birdnet-go/config/debug_*` Clean out debug files I never look at
