### DISCUSSION TITLE
birdnet.log?

### DISCUSSION THREAD

**Discussion by dziban303** [tphakala/birdnet-go#718] [Q&A]
Hi, I'm curious about the birdnet.log file mentioned in config.yaml, in the `main:` section there is an entry:

```yaml
debug: false 
main:
    name: Birdnet-Go
    timeas24h: true
    log:
        enabled: true
        path: birdnet.log
        rotation: daily
        maxsize: 1048576
        rotationday: Sunday
birdnet: 
...
```

I can't find any such file within the container or anywhere else, and was wondering about this setting. Though it just occurred to me that this may only be created if `debug: true` is set.

I realize it's distinct from `birdnet.txt`, and the individual logs like `diskmanager.log`.
