### DISCUSSION TITLE
Recommended settings ?

### DISCUSSION THREAD

**Discussion by jpmurray** [tphakala/birdnet-go#735] [Q&A] [answered]
I'm curently testing Birdnet-Go because I really like the UI, but I'm curently getting _way_ less results than I was getting with Birdnet-Pi... Is there some recommended settings I should be setting that I might have overlooked ?

**Comment by tphakala** [comment]
What is BirdNET overlap value set to on your system? BirdNET-Go has false positive mitigation system which may reduce total number of detections, it is documented in https://github.com/tphakala/birdnet-go/blob/main/doc/wiki/guide.md#deep-detection.

In essence if you set BirdNET Overlap to 0.0 then BirdNET-Go reports every detection on first hit, you may see higher number of detections but also much higher number of false positive matches.

**Reply by jpmurray** [reply]
I think I might be confused with all the thresold...

So far, my BirdNet settings are sensitivity 1.5 (my feed is from a Wyze RTSP cam, so not the best!), Threshold 0.7 and Overlap 0. Dynamic Threshold are trigger 0.9, mininum 0.2... But then I also have the range filter with a threshold of 0.6.

Is there an order of precedence on each of them ?

**Reply by tao54tao** [reply]
I just set up my own instance of BirdNet-Go using an RTSP cam as well.  I am interested if you have found some settings that work well for you as I am also getting only a handful of detections.

**Reply by jpmurray** [reply]
I got the config under here. I'm getting more hit for same spicies than I had before, but it is still *way* less than I get with Birdnet-Pi at the moment.

(For this day, 20 detection with Birdnet-go against 109 with Birdnet-Pi.)

What kills me is that one detects a couple spicies that the other won't, and vice versa. Like BN-Go is catching a lot of crows but no mourning dove, and BN-Pi got a crow once and a lot of doves...

```yaml
birdnet:
    sensitivity: 1.2
    threshold: 0.3
    overlap: 2.8
    rangefilter:
        debug: false
        model: latest
        threshold: 0.6
dynamicthreshold:
        trigger: 0.9
        min: 0.2
        validhours: 48
```
