### ISSUE TITLE
bug (minor) Web UI not working correctly if default port is changed 

### ISSUE THREAD

**Issue by PovilasID** [tphakala/birdnet-go#169]
Hey,

I tested running this in docker and changed native webui port
```
webserver:
  enabled: true         # true to enable web server
  port: 8778            # port for web server
  autotls: false        # true to enable auto TLS
```
UI loads but not entirely. I get detections page just fine but if try to open Settings I get:
```
{
"message": "Internal Server Error"
}
```
Also "Nothing here yet .." in stats and logs pages.

BTW I tried setting webui to false... it sill started up. Very persistent! 😄 But maybe not ideal if trying to reduce some resource consumption.
