### ISSUE TITLE
Confidence level Threshold

### ISSUE THREAD

**Issue by matthew73210** [tphakala/birdnet-go#239]
Hello,

Right now i have my threshold set at 0.8 

```
# BirdNET model specific settings
birdnet:
    sensitivity: !!float 1 # sigmoid sensitivity, 0.1 to 1.5
    threshold: 0.8 # threshold for prediction confidence to report, 0.0 to 1.0
    overlap: 0.0 # overlap between chunks, 0.0 to 2.9
    threads: 0 # 0 to use all available CPU threads
    locale: en # language to use for labels
    latitude: xxx # latitude of recording location for prediction filtering
    longitude: xxx # longitude of recording location for prediction filtering
    rangefilter:
        version: latest # model to use for range filter: "latest" or "legacy" for previous model
        threshold: 0.01 # rangefilter species occurrence threshold
```

Yet i'm getting the following :

<img width="1094" alt="Screenshot 2024-06-29 at 8 29 05 AM" src="https://github.com/tphakala/birdnet-go/assets/19491784/fb5a2be5-9af5-4b1d-bbdc-5bb07275f29b">

Is the perhaps related to the dynamic threshold, or is this still not implemented in the main repo?
