### ISSUE TITLE
cannot parse 'Main.Log.RotationDay' as int: strconv.ParseInt: parsing "Sunday": invalid syntax

### ISSUE THREAD

**Issue by jasonmadigan** [tphakala/birdnet-go#277]
Giving the latest `dev` images a spin, seeing:

```
birdnet-go  | 2024/09/11 20:38:47 Error loading settings: error unmarshaling config into struct: 1 error(s) decoding:
birdnet-go  |
birdnet-go  | * cannot parse 'Main.Log.RotationDay' as int: strconv.ParseInt: parsing "Sunday": invalid syntax
```

My compose:

```
...
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:dev
    container_name: birdnet-go
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Dublin
    volumes:
      - /mnt/birdnetgo/config:/config
      - /mnt/birdnetgo/data:/data
    command: >
      realtime
      --rtsp rtsp://admin:***@192.168.*.*:554/Streaming/Channels/3/
```

Oddly, this was working before. I've recreated the `/config` + `/data` folders. I don't recall having to have a default config file, but maybe I need to.
