### ISSUE TITLE
Documenting Web UI Usage

### ISSUE THREAD

**Issue by arnydo** [tphakala/birdnet-go#45]
Hi! Fantastic project BTW!

I am setting up an instance here and I am unable to determine how to get the Web UI running. Do you have any documentation on setting this up?

Thank you.

**Comment by tphakala** [comment]
Hi, thanks for feedback. Documentation is lacking, I have nothing on Web UI just yet, but it should be very simple.

Web server is enabled by default in config, so if you just run "birdnet-go realtime" you should see something like this:
```
./birdnet-go realtime
Read config file: /etc/birdnet-go/config.yaml
BirdNET GLOBAL 6K V2.4 FP32 model initialized, using 4 threads of available 4 CPUs
Starting BirdNET-Go Analyzer in realtime mode
Threshold: 0.5, sensitivity: 1.5, interval: 15
[2024-03-05T17:51:56+02:00] [INFO] ⇨ **http server started on [::]:8080**
```
Web UI is accessible on port 8080 of your host system.

**Comment by arnydo** [comment]
Hey @tphakala  thank you so much for the prompt response.

I am running the same as you but it isn't loading the UI.
It is the default config running on Linux.

```
./birdnet-go realtime          
Read config file: /home/arnydo/.config/birdnet-go/config.yaml
error reading species conficende config: species confidence file 'species_config.csv' not found
BirdNET GLOBAL 6K V2.4 FP32 model initialized, using 24 threads of available 24 CPUs
Starting BirdNET-Go Analyzer in realtime mode
Threshold: 0.8, sensitivity: 1, interval: 15
Listening ...
11:02:21 Engine 0.86
```

**Comment by tphakala** [comment]
According to that output web server is not starting.

Can you check that this section is included in /home/arnydo/.config/birdnet-go/config.yaml?

```
webserver:
  enabled: true		# true to enable web server
  port: 8080		# port for web server
  autotls: false		# true to enable auto TLS
  log:
    enabled: true	# true to enable log file
    path: webui.log	# path to log file
    rotation: daily	# daily, weekly or size
    maxsize: 1048576	# max size in bytes for size rotation
    rotationday: 0	# day of the week for weekly rotation, 0 = Sunday
```

If you have used version of BirdNET-Go without web ui this is likely missing from config, I have not yet implemented any method for updating config across versions 😞 

If you delete existing config file a new config with new default values will be created for you, just make sure to make a note of important settings you may have done.
