### ISSUE TITLE
Timestamps are GMT (I set America/New_York)

### ISSUE THREAD

**Issue by y8s** [tphakala/birdnet-go#655]
## Issue Type
- [ ] Bug report

## Description
Using docker compose when setting TZ it appears to ignore the local time and uses GMT.

## Steps to Reproduce (for bugs)
1. make compose file (via dockge)
2. start it, look at watch, wait for birds to cheep
3. see timestamp is +4 hrs compared to my watch

## Expected behavior
timestamp to match my local tz

## Actual behavior
7pm chirps and cheeps logged as 23:00 chirps and cheeps. all historical bird sounds are shifted as well.

## Screenshots

![Image](https://github.com/user-attachments/assets/e9e7efc2-6566-4995-80af-e08c228941e9)

### Version Information (build date)
Provide the following line from your system:

compose file
```
services:
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:nightly-20250407
    # is actually v0.6.4
    ports:
      - 8080:8080
    environment:
      - TZ="America/New_York"
    volumes:
      - ./config:/config
      - ./data:/data
    command: realtime --rtsp rtsp://user@pass@/<redacted ip>:554/cam
networks: {}
```

### System Information
- Device: 
  - [ ] old dell
- OS: proxmox 8.3.5
- OS Version: debian bookworm vm

### For Non-Raspberry Pi Linux Users
Have you tested with the latest dev branch container image?
- [ ] Yes
It doesn't run. everything newer than this version has some `realtime is not in the path` error.

If not, first test with the latest dev branch container image and see if the issue is already fixed.
```
$ docker pull ghcr.io/tphakala/birdnet-go:dev
```
I tried all nightlies from 20250407 to 20250421 but only 20250407 works.

## Additional context
none

## Possible Solution
none
