### ISSUE TITLE
UID/GID ownership issues

### ISSUE THREAD

**Issue by xconverge** [tphakala/birdnet-go#657]
Starting with https://github.com/tphakala/birdnet-go/pull/636 just wanted to make you aware, I am fine to stick to v0.6.4 for now

I can't run the nightlies due to the UID/GID changes

I have kind of a weird setup related to UID/GID

```
    birdnet-go:
        container_name: birdnet-go
        image: ghcr.io/tphakala/birdnet-go:(latest/v0.6.4 is fine, newer nightlies are not)
        environment:
            - TZ=${TZ}
            #- BIRDNET_UID=1000
            #- BIRDNET_GID=1000
        volumes:
            - "${DOCKER_VOLUMES}/birdnet-go/config:/config"
            - "/mnt/files/birds:/data"
        ports:
            - 9099:8080
        restart: always
```

My `/data` folder is on a synology NAS with a nfs share that is mounted to my Debian system running docker

Maybe I could move the db to my ssd and only keep the .wav files on the NFS mount somehow?

but whether I use BIRDNET_UID/GID as the defaults or 1000/1000 or the values which I think would make sense for the NFS mount and how I have it setup, I get forbidden chown commands all over the place and the container never starts up successfully

I have tried 1024 and 100 as well which is what should be right
```
/mnt/files/birds$ ls -ln
total 14020
-rwxrwxrwx 1 1024 100 10145792 Apr 23 15:46 birdnet.db
-rwxrwxrwx 1 1024 100    32768 Apr 23 19:13 birdnet.db-shm
-rwxrwxrwx 1 1024 100  4177712 Apr 23 19:13 birdnet.db-wal
drwxrwxrwx 1 1024 100        8 Feb 12 07:04 clips
```
