### ISSUE TITLE
[bug]  exec: "realtime": executable file not found in $PATH

### ISSUE THREAD

**Issue by PovilasID** [tphakala/birdnet-go#661]
## Issue Type
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support

## Description
Fails to launch.

## Steps to Reproduce (for bugs)
1. Pull latest image
2. docker compose up -d

## Expected behavior
To start the container

## Actual behavior
exits with code 1

### Version Information (build date)
Current dev build [afb7adb3e0cdbcae7178b82cbd013ac8fc681c74](https://github.com/users/tphakala/packages/container/birdnet-go/402083256?tag=afb7adb3e0cdbcae7178b82cbd013ac8fc681c74)

### System Information
- Device: 
  - [ ] Raspberry Pi (specify model, e.g., Raspberry Pi 4 Model B)
  - [ ] Other SBC (please specify)
  - [x ] PC/Server (please specify)
- OS: OpwnWRT
Running in docker

### LOGS
I was running container in host mode previously and after update I got this log:
```
stdout: Starting BirdNET-Go with UID:1000, GID:1000
stdout: Creating group birdnet with GID 1000
stdout: Adding group `birdnet' (GID 1000) ...
stdout: Done.
stdout: Creating user birdnet with UID 1000
stdout: Adding user `birdnet' ...
stdout: Adding new user `birdnet' (1000) with group `birdnet (1000)' ...
stdout: Creating home directory `/home/birdnet' ...
stdout: Copying files from `/etc/skel' ...
stdout: Adding new user `birdnet' to supplemental / extra groups `users' ...
stdout: Adding user `birdnet' to group `users' ...
stdout: Starting BirdNET-Go as user birdnet (1000:1000)
stderr: error: exec: "realtime": executable file not found in $PATH
```

I was not using user setting but I tried to but still got same error   `- BIRDNET_UID=0`  ` - BIRDNET_GID=0`
```
stdout: Starting BirdNET-Go with UID:0, GID:0
stdout: Starting BirdNET-Go as user root (0:0)
stderr: error: exec: "realtime": executable file not found in $PATH
```
 ### Docker compose file
```
version: "3.9"
services:
  birdnet:
    image: ghcr.io/tphakala/birdnet-go:dev 
    container_name: birdnet
    network_mode: host
    volumes:
      - ./config:/config
      - ./data:/data
    command: realtime --rtsp rtsp://192.168.1.1:/doors?audio=any 
```

## Additional context
Possibly related issue https://github.com/tphakala/birdnet-go/issues/657 Something has changed in user handling
## Possible Solution
Reverting to older versions worked
